apiVersion: v1
kind: Pod
metadata:
  name: pod-wallet-api
  labels:
    type: backend-wallet-api
spec:
  containers:
    - name: wallet-api
      image: dherkyan/wallet-api:25
      env:
        - name: PROFILES_ACTIVE
          value: dev
        - name: H2_WEB_ALLOW_OTHERS
          value: "true"
      ports:
        - containerPort: 8080 # porta da aplicação
---
apiVersion: v1
kind: Service
metadata:
  name: service-wallet-api
spec:
  type: ClusterIP
  selector:
    type: backend-wallet-api
  ports:
    - name: http
      targetPort: 8080 # porta da aplicação
      port: 8080 # porta da aplicação
#      nodePort: 30008 # porta que será exporta externamente