create table tb04_wallet_item (
  id bigint generated by default as identity,
  data_cadastro timestamp not null,
  descricao varchar(255) not null,
  tipo varchar(255) not null,
  valor decimal(19, 2) not null,
  wallet bigint,
  primary key (id)
)